### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by aracnus** [minetest-technic/technic#105]
There are some missing textures on technic:

- technic_akalin_dust.png
- technic_alatro_dust.png
- technic_arol_dust.png
- technic_talinite_dust.png
- technic_template_replacer.png
- technic_template_tool.png

**Comment by VanessaE** [comment]
This appears to have been fixed quite some time ago.

**Comment by HybridDog** [comment]
lt is not fixed, templates are just disabled.
