### ISSUE TITLE
Allow battery boxes to also be used on low-voltage circuits

### ISSUE THREAD

**Issue by Susurrus** [minetest-technic/technic#110]
If you have an LV power circuit at the start, but have gotten lvl2 or lvl3 power tools, it can take an exceedingly long time to charge them since you're limited to a 50k-charge battery box. It'd be nice to either a) have upgradable battery boxes or b) use the MV/HV battery boxes for storage.

I propose allowing the higher-voltage battery boxes to be used at their level or lower. I think this is also consistent with their construction, as the MV boxes have an MV transformer, and LV transformers in all of its consituent LV boxes (the HV box follows this pattern for LV, MV, and HV circuits). So it would make sense that these boxes would work on any voltage level below their own design. A way to penalize this a little is to lower their charge/discharge rates by 10% per level difference. So a HV battery box on an LV system would only charge at 80% of how fast an LV battery box would charge on that same system, since it has to go through two sets of transformers to the batteries, each imposing a 10% inefficiency.

**Comment by VanessaE** [comment]
Clearly something that is undesirable.
