### ISSUE TITLE
[Suggestion] Overclockers to replace LV,MV,HV versions of machines

### ISSUE THREAD

**Issue by VileTouch** [minetest-technic/technic#127]
Things like furnaces, generators, grinders, compressors, extractors don't really need to have 3 versions of the same block. so what i propose is **Upgrade modules**. stackable (and expensive) items that can be installed in any machine to upgrade efficiency by a certain amount.
_(quote from ic2 wiki)_
**Overclocker Upgrades**
An overclocker upgrade can be used to speed up machines at the cost of higher energy consumption. Place one or more overclocker upgrades into the four right-most slots to upgrade a machine.

Each upgrade reduces the operating time to 70% of the previous value and increases energy consumption by 60%. The overclocker upgrade's effects stack exponentially. For example, two upgrades makes the machine operate at (0.7)^2 = 0.49 times normal time (100% faster) and use 1.6^2 = 2.56 times the energy (139% more). 8 of them will run the machine at over 8 times normal speed, and use over 43 times as much EU.

Overclocker upgrades result in poorer energy efficiency (more EU will be consumed per operation). This results in a 12 percent increase in energy per operation per upgrade (0.7*1.6 = 1.12, (1.12)^10 = 3.11 ). While building multiple machines makes better use of a limited energy supply, but overclocking allows for reduced space and wiring requirements when time or compact construction are more important or energy is plentiful. The reduced efficiency can be mitigated by combining both approaches, dividing a number of overclocker upgrades evenly between a handful of machines.

An overclocked machine's speed cannot exceed 1 operation per tick, so adding additional overclocker upgrades beyond that point is useless. 

**Transformer Upgrades**
A transformer upgrade can be used to upgrade a machine's power input rate or tier. Place one or two transformer upgrades into the four right-most slots to upgrade a machine.

One upgrade enables a tier 1 machine to receive 128EU/t. Two upgrades enables it to receive 512EU/t and three for More than 512 EU

**Energy Storage Upgrades**
An energy storage upgrade can be used to upgrade a machine's internal power storage. Place one or more energy storage upgrades into the four right-most slots to upgrade a machine. Each upgrade increases the storage capacity by 10,000 EU. Its main purpose is for use when a machine's energy consumption becomes too large for its internal storage to handle; this only happens when an extreme number of overclocker upgrades are present.

**Comment by mrsteyk** [comment]
I dont feel ok with this idea! This will make OS technic look like CS ic2! I dont like that idea, unless someone will make transvector- or tesseract-kinda stuff!

**Comment by VanessaE** [comment]
I am not in favor of this idea either, and these are machines, not CPUs.
