### ISSUE TITLE
frames cheat

### ISSUE THREAD

**Issue by HybridDog** [minetest-technic/technic#170]
https://imgrush.com/TEV8R6pJ-dbY
If you place a frame, then place something into it, you have a node with object which you can use to get infinite nodes. You just need to right click on the frame entity, and not on the node inside the frame.

**Comment by VanessaE** [comment]
Can't reproduce this in current Technic.

**Comment by t4im** [comment]
Never could reproduce this particular one either, but i had a similar duplication issue with templates instead of frames. They certainly need *some* repair. See the list in #217

**Comment by HybridDog** [comment]
l just tested it, it still works, see the video.

**Comment by HybridDog** [comment]
Is this fixed yet?

**Comment by BobFred7** [comment]
The link now redirects to what appear to be scam websites

**Comment by HybridDog** [comment]
> The link now redirects to what appear to be scam websites

Thanks for the information. I've removed it now and tested it again. The problem is still not fixed.
