### ISSUE TITLE
Make chests more independent

### ISSUE THREAD

**Issue by Rogier-5** [minetest-technic/technic#192]
Hi,

Could you consider making the chests more independent of other mods ?

As far as I can judge, three minor changes would be needed.
- Make the dependency on pipeworks optional. There seems to be no chests code actually using it directly
- Add a soft dependency on moreores (there is none now), and make the code for mithril and silver chests check for the existence of moreores before registering anything.
- Transfer two images from techinc/textures to technic_chests/textures: technic_form_bg.png and technic_main_inventory.png

If desired, I can prepare the patches and make a pull request.

**Comment by VanessaE** [comment]
Patches are welcome, so long as they don't break any existing functionality.  Chests can receive items from incoming tubes, hence the dependency on pipeworks.

**Comment by t4im** [comment]
the unified inventory dependency was already resolved with d452d16 by transferring mentioned textures

**Comment by est31** [comment]
I think what Rogier is meaning with the third point is that technic chests right now depends on technic (without stating it in the depends.txt). The commit d452d16fa6a0364e0c8e171a4b333d6b85e0c519 placed them into the texture directory of the wrong mod. It was mainly targeted at making technic independent from U-I. Haven't realized that the should have been moved to `technic_chests`.

**Comment by Rogier-5** [comment]
Re est31: indeed.
I found no other uses within technic, than the chests code...

I'll create patches, test them using pipeworks, and submit a pull request for the changes.

**Comment by Rogier-5** [comment]
Created pull request https://github.com/minetest-technic/technic/pull/218
