### ISSUE TITLE
Make wrench more independent

### ISSUE THREAD

**Issue by Rogier-5** [minetest-technic/technic#193]
Hi,

Could you consider making the wrench more independent of technic, so that it can be used without the rest of technic.

As far as I can determine, three minor changes are needed:
- Make the dependencies on other parts of technic optional
- In wrench:register_node(), check whether the node being registered to the wrench is registered to minetest. If not, then don't register it.
- in technic.lua, before cycling through the table technic.machines, verify that it exists and is a table.

If desired, I can prepare the patches and submit a merge request.

**Comment by VanessaE** [comment]
Patches are welcome.

**Comment by Rogier-5** [comment]
I'll create the patches and submit a pull request.

**Comment by Rogier-5** [comment]
I submitted a pull request: https://github.com/minetest-technic/technic/pull/212
