### ISSUE TITLE
Which License?

### ISSUE THREAD

**Issue by est31** [minetest-technic/technic#194]
I can't find any license for the technic code in the [technic/README.md](https://github.com/minetest-technic/technic/blob/master/technic/README.md) file. Which is it? Do we have to ask all contributors? In fact, every mod except the `technic_chests` mod is missing a license.

**Comment by VanessaE** [comment]
Technic is LGPLv2+ unless one of its components carries a separate license.  That's specified in the forum post, but you're right that it really should be in the README.

**Comment by VanessaE** [comment]
28ed3b29a3d7749ec129d3f40e0b61de1c770aa6
