### ISSUE TITLE
Weird Sulfur Generation

### ISSUE THREAD

**Issue by MT-Modder** [minetest-technic/technic#215]
Is this normal?

![screenshot_29384563](https://cloud.githubusercontent.com/assets/7414772/6675579/dd458ac6-cbf7-11e4-90dd-68ee7d787130.png)
![screenshot_29375865](https://cloud.githubusercontent.com/assets/7414772/6675580/dd46c756-cbf7-11e4-8ba8-907b74444b50.png)

**Comment by est31** [comment]
is swimming in lava normal? :P

**Comment by MT-Modder** [comment]
lol In creative mode with damage off it is :P

**Comment by t4im** [comment]
I think it's intentional. Yes.

**Comment by MT-Modder** [comment]
Okay I wasn't sure. It looked kinda weird seeing all that ore :smile:. At first I thought it was mese and I said "Holy $%@#"
