### ISSUE TITLE
technic/Quarry makes server stall

### ISSUE THREAD

**Issue by yo-we** [minetest-technic/technic#219]
Quarry makes server stall under different circumstances. One of which was the presence of bones of a player who died inside the volume the Quarry digs.
The server stalls as soon as this Quarry is active i.e. as soon as a player is somewhere around. 
Once that happened, each time the player logs, the server stalls immediately.

Other server reboots where due to the Quarry, too, but I do not have the logs available anymore. We had to entirely remove any possibility to interact with Quarry.

**Comment by VanessaE** [comment]
This should be fixed by now.
