### ISSUE TITLE
Crash when digging cable

### ISSUE THREAD

**Issue by neko259** [minetest-technic/technic#220]
```
technic/technic/machines/register/common.lua:172: attempt to call field 'after_dig' (a nil value)
```

**Comment by HybridDog** [comment]
Can you give more information?

**Comment by neko259** [comment]
No, I can't. This is all I had in log and now I even don't have it anymore.

**Comment by HybridDog** [comment]
ok

**Comment by ShadowNinja** [comment]
This appears to be because you have an old pipeworks version without `after_dig`.  Please update pipeworks and check if the issue is gone.
