### ISSUE TITLE
Missing radiation attenuation for lead block

### ISSUE THREAD

**Issue by JDCodeIt** [minetest-technic/technic#226]
I could not find a reference for radiation resistance for lead block, although this seems an obvious building material for the waste storage.  A 1955 paper on the subject shows a halving of gama transmission in about a 1/2 inch of lead, so about 80 halvings in a meter might be a good value.

proposed fix would add an entry to the table in nuclear_reactor.lua

local default_radiation_resistance_per_node = {
...
	["technic:granite"] = 18,
	["technic:lead_block"] = 80,
	["technic:marble"] = 18,
...

**Comment by VanessaE** [comment]
e7d06b33d172ca48d7ea6bb7f99dd93c0a7cc2e2
