### ISSUE TITLE
Zapping corium_source with laser remove it

### ISSUE THREAD

**Issue by asl97** [minetest-technic/technic#227]
are we suppose to be able to just laser a corium_source to clear it?

that seem way too easy.

**Comment by HybridDog** [comment]
l always take it with a bucket and use it as protection against other players.

**Comment by asl97** [comment]
@HybridDog that's not really the point

**Comment by HybridDog** [comment]
l assume the laser vaporizes the source node and it becomes a gas, which is air in minetest, even if it's radioactive

**Comment by asl97** [comment]
lava doesn't vaporize, why should corium?

**Comment by VanessaE** [comment]
As corium is highly radioactive, and for most servers would serve no purpose at all to be able to pick it up with the laser, treating it as "vaporized" makes sense here.

**Comment by HybridDog** [comment]
You could make mining lasers give the furnace result(s) of the dug node(s)

**Comment by asl97** [comment]
@HybridDog not really the point again.

@VanessaE i ain't saying that the laser should pick it up, i am saying that it should just leave it alone like lava.

why don't lava "vaporize" when corium does?
