### ISSUE TITLE
Missing screenshot and description files

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest-technic/technic#240]
Currently this mod does not have a screenshot or description file included. Both are used when displaying the mod in the Mods tab of the main menu of Minetest.

The screenshot should be in a 3:2 aspect ratio, be named "screenshot.png", and be placed in the main directory of the mod.

The description file should be a small text file with a short description of the mod, be named "description.txt", and be placed in the main directory of the mod.

**Comment by VanessaE** [comment]
The "mod store" in minetest has been discontinued, pending a better solution some day.

**Comment by ShadowNinja** [comment]
However, a `name` in `mod.conf` to support different folder names would be good.
