### ISSUE TITLE
recipe for teleport_tube_1 displayed in craftguide but doesnt work

### ISSUE THREAD

**Issue by tchncs** [minetest-technic/technic#244]
```
minetest.register_craft( {
        output = "pipeworks:teleport_tube_1 2",
        recipe = {
                { "homedecor:plastic_sheeting", "homedecor:plastic_sheeting", "homedecor:plastic_sheeting" },
                { "default:desert_stone", "default:mese", "default:desert_stone" },
                { "homedecor:plastic_sheeting", "homedecor:plastic_sheeting", "homedecor:plastic_sheeting" }
        },
})
```

...is in Craft Guide, but if you want to **craft** it, you have an emty Output.

**Comment by t4im** [comment]
That is actually an unified inventory bug, not a technic bug. Technic intentionally overwrites that recipe to deactivate it. It is not supposed to be craftable to begin with. However Unified Inventory still displays it, though it shouldn't.

**Comment by tchncs** [comment]
I this case a craft guide "bug" - we doesnt use unified inventory...
So i think i just comment the technic recipe away, because my players are very angry :D

**Comment by t4im** [comment]
Hm, yea the engine doesn't provide much for deactivation here. So every inventory system probably has a similar issue with it.

**Comment by tchncs** [comment]
Okey i understand...but is there any - or different: where is the way to change the recipe back?
It doesnt work to comment the recipe from Technic away...replacing seems doesnt work also?

I want to totally deactivate the pipeworks things in this mod.
In my (our) opinion there should be an option in the config.lua :-(

**Comment by t4im** [comment]
You can leave the technic one in. The "defusion" of the pipeworks recipe happens after [line 166](https://github.com/minetest-technic/technic/blob/master/technic/crafts.lua#L166)

**Comment by tchncs** [comment]
Oh my god, how i didn't saw that :'(
Im so sorry about your wasted time because of me...
