### ISSUE TITLE
Content in locked Chests is viewable

### ISSUE THREAD

**Issue by tchncs** [minetest-technic/technic#245]
The Content in locked Chests is viewable.
This happens only on new placed Chests.

Players seems apparently not able to put Stuff away, but its not very nice nevertheless.

**Comment by thatgraemeguy** [comment]
I'm not sure if this is considered a bug, technic's locked chests have always been viewable as far as I can recall. I see no mention in the manual that they are supposed to be completely inaccessible.

**Comment by tchncs** [comment]
I cant say if its wanted by the technic maintainers.
The are just confused because the regular wooden chests are completly unaccessable.
And it will the players also confusing when there old chests be regular locked, but other guys can see the stuff.

On the other hand - if you have a old chest in real life, what will you say when other people can see in it? ;-)

**Comment by t4im** [comment]
The exchange of the locking mechanism is intentional (see also 1d7cb740538b1d97f29d7771ec5cd9435591128f) to align it with other inventory nodes. Which feels less laggy, because you don't need to wait for the server rountrip to check for permissions before actually doing inventory operations.
The thing about unlocked chests being unaccessable however doesn't sound too good. Could you elaborate?

**Comment by tchncs** [comment]
Oh, i think you understood me wrong @t4im: 
*We are just confused because the regular wooden chests are completly unaccessable.*
I wanted to say, players are unable to look in it, like it is by the default onces.
Until you replaced it - than you have the chests there viewable.

So its a performance question?
Hmm so we have to live with it...on the other hand - the performance with the regular onces was not bad.
Thank you, for your explanation.

**Comment by t4im** [comment]
Less performance more "reaction time" or latency. When the server is under load players don't have to wait but can queue several inventory changes quickly after each other, and the server can catch up after.
