### ISSUE TITLE
Make blast resistant concrete resists dungeon master blasts

### ISSUE THREAD

**Issue by pyrollo** [minetest-technic/technic#246]
Is it possible to add Blast Resistant Concrete node to the unbreakable group ? 

technic/concrete/init.lua line 94 :

- 	groups={cracky=1, level=3, concrete=1},
+ 	groups={cracky=1, level=3, concrete=1, unbreakable=1},

So blast resistant concrete wont be destroy by tenplus1 dungeon masters.

**Comment by t4im** [comment]
It _is_ breakable though. But it would probably make sense overwriting [on_blast](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3251), provided @tenplus1 makes use of that in the mod (which i couldn't find right now).

**Comment by Ekdohibs** [comment]
This should be in on_blast indeed, to make it resistant to tnt too.

**Comment by MT-Modder** [comment]
The mobs PR: https://github.com/tenplus1/mobs/pull/47 has been merged. Maybe now the above linked PR can be merged as well?

**Comment by ShadowNinja** [comment]
0c144cd75c638f1f1c67ae91973f3ff8ffc781dd
