### ISSUE TITLE
Conducting Tube for LV,MV,HV cable

### ISSUE THREAD

**Issue by DoyleChris** [minetest-technic/technic#269]
In pipeworks theres a conducting tube that can send Mesecon signal made this way.

{plastic_sheet,plastic_sheet,plastic_sheet]
{mesecon,mesecon,mesecon                   ]
{plastic_sheet,plastic_sheet,plastic_sheet]

My idea would be to make a tube that can send EU's through it, crafting example.

{plastic_sheet,plastic_sheet,plastic_sheet]
{LV_cable,                                 ,LV_cable]
{plastic_sheet,plastic_sheet,plastic_sheet]

And use LV, MV, or HV cable.

**Comment by VanessaE** [comment]
Cables are supposed to carry huge amounts of power, while a conductor tube is only meant to carry a low-current digital signal. As such, a tube that would appear to carry enough current would be huge... and wouldn't look like a tube anymore. :P
