### ISSUE TITLE
mining laser crasher server when digging upgraded machines

### ISSUE THREAD

**Issue by NathanSalapat** [minetest-technic/technic#270]
can be fixed by changing line 144 in technic/technic/machines/register/common.lua to read 
```Lua
if not inv:is_empty("src") or not inv:is_empty("dst") or not inv:is_empty("upgrade1") or not inv:is_empty("upgrade2") then
```
rather than
```Lua
if not inv:is_empty("src") or not inv:is_empty("dst") then
```
This makes the digging check that both upgrade slots if available are empty, machines without upgrades still dig just fine.

**Comment by tenplus1** [comment]
after_dig handles the drops: https://github.com/minetest-technic/technic/pull/273

**Comment by Ekdohibs** [comment]
https://github.com/minetest-technic/technic/commit/322615542e570f6363c7006b90f334e9ffd722c8
