### ISSUE TITLE
Mineral generation conflict

### ISSUE THREAD

**Issue by numberZero** [minetest-technic/technic#274]
(in file `technic_worldgen/mg.lua`)
zinc and lead have exactly the same generation parameters, except of `numperblock`, but _including_ `seeddiff`. Is it intentional?

**Comment by VanessaE** [comment]
This is no longer valid since having merged #258.

**Comment by numberZero** [comment]
@VanessaE still valid, as it regards `mg`-specific generation (`technic_worldgen/mg.lua`) and #258 is about builtin map generation settings (`technic_worldgen/oregen.lua`).

**Comment by VanessaE** [comment]
Guess I misread, sorry.

**Comment by mrsteyk** [comment]
@numberZero, PR #333 should fix the rareness completly.

**Comment by VanessaE** [comment]
#333 has been merged.  What else needs done to close this issue?

**Comment by numberZero** [comment]
@mrsteyk please don't make PRs anymore.
@VanessaE these PRs are entirely unrelated to this bug. #336 is the fix.

**Comment by VanessaE** [comment]
Merged.
