### ISSUE TITLE
Lead explanation needed in documentation

### ISSUE THREAD

**Issue by expertmm** [minetest-technic/technic#278]
At https://github.com/minetest-technic/technic/blob/master/manual.md
The manual says Lead is not in the game but radiation shielding would be a certain value.
Could you improve the manual to add where lead can be mined, and rephrase the existing statement?

**Comment by VanessaE** [comment]
Please consider editing the file yourself and submitting a pull request with your changes.

**Comment by expertmm** [comment]
Sure, here it is: https://github.com/minetest-technic/technic/pull/318

**Comment by HybridDog** [comment]
Can this be closed?
