### ISSUE TITLE
Alternate nuclear reactor model

### ISSUE THREAD

**Issue by amianthoidal** [minetest-technic/technic#279]
I had an idea while getting damaged by radioactive in-game. I'm not sure if it's feasible or even good. Nuclear reactors could be represented by blocks that interact with each other by radioactivity and heat.

For example, a 'core' block would emit radioactivity and produce excess heat within itself, while a 'turbine' block would absorb radioactivity as heat, producing electricity from it and 'emitting' heat-reducing rays to cool down cores. Of course, if the cores get too hot, they meltdown.

The reactor would have to be enclosed in lead to keep players safe, and the players would insert/extract each core's control rods using mesecons or something (from a safe distance).

**Comment by numberZero** [comment]
That is you want a more realistic reactor. That’s fine but is much more complex than the current implementation. We need someone who can program that.

**Comment by amianthoidal** [comment]
I'm going to try getting a working implementation at [https://github.com/amianthoidal/technic_steam](url). I think I should be able to get something to work just by re-using the code already in Technic. However I have no experience with the Minetest engine, so my approach might turn out to be unworkable!

**Comment by VanessaE** [comment]
No word from the author in ages, and the link provided in his last post is dead now.  Closing...
