### ISSUE TITLE
Re-battery requires moreores:tin_ingot, but moreores is not in depends.txt

### ISSUE THREAD

**Issue by thePalindrome** [minetest-technic/technic#280]
As the title says, but technic:tin_dust is defined.

Is moreores to be made required, or will these recipies change?

**Comment by numberZero** [comment]
The manual says:
> The technic modpack depends on some other modpacks:
...
> * moreores, which provides some additional ore types

Actually this mod seems to work fine without `moreores` (and the most important things are still craftable), so I think `moreores` should be added as a soft dependency

**Comment by thePalindrome** [comment]
Well the issue I had was that without tin RE-batteries were uncraftable, and solar panels required silver wire, which needed silver.

The mod "works" without more ores, you just can't craft a lot of things.

**Comment by VanessaE** [comment]
I don't really see a problem here, and a "soft" dependency isn't necessary where recipes alone are concerned.

**Comment by thePalindrome** [comment]
I think I'm missing something, because without moreores the red and green energy crystals are uncraftable and every mining drill is uncraftable. If they aren't craftable then why register them?

I just don't see the point of having uncraftable items existing ( for an example, see the Infinitato in the MC mod Avaritia, which is only registered if Botania is installed)

Although given that drills become non-existent by this arrangement, perhaps supply a different recipe if moreores isn't installed?

**Comment by numberZero** [comment]
> If they aren't craftable then why register them?

That may only be useful in the case some other mod registers its own recipes for technic items.

**Comment by thatgraemeguy** [comment]
I don't understand how this can be a "Won't fix" if lack of tin leaves you with items that simply cannot be crafted.

**Comment by VanessaE** [comment]
Because you can still acquire the wayward items via creative mode, /giveme, or from someone selling them (on my servers, it's common for admins to set up shops that sell hard-to-find/hard-to-make items).

**Comment by thePalindrome** [comment]
The first two suggestions on those feel like cheating, while the last one may not be possible without external mods.
All three of those feel like extra work just to play the mod, which I'd say is beside the point (contrast to MC mods, which you just drop into your server folder and start up)

**Comment by VanessaE** [comment]
Also I need to point out from the Minetest forum post for this mod, as written by RBA:

> Not strictly required, but required for some recipes:
> * [moreores](https://forum.minetest.net/viewtopic.php?id=549) - [download ZIP](https://gitorious.com/calinou/moreores/archive/master.zip)
> * [mesecons](http://mesecons.net/) - [download ZIP](https://github.com/Jeija/minetest-mod-mesecons/archive/master.zip)

(that was tricky to convert from bbcode to markdown :smile: )
