### ISSUE TITLE
Add defualt music for the music player

### ISSUE THREAD

**Issue by benrob0329** [minetest-technic/technic#281]
It's somewhat confusing to have a music player, with no music...so why not have some CC0/Public Domain music added by default?

I'll search around and see what I can find.

If nothing else the wiki should be updated.

**Comment by VanessaE** [comment]
Adding any kind of default music to the player would drastically increase the size of the modpack (and hence, the download time on any server using it).  Rather, it was intended that the user supply their own music files in one of Minetest's directories.
