### ISSUE TITLE
Revamp the wiki

### ISSUE THREAD

**Issue by benrob0329** [minetest-technic/technic#282]
I would like to update the technic wiki, but have no idea where to start.

(I guess wikis are just editable then? I added a h1 tag to the main page, no pull request or anything :confused: )

I suppose the best place to start would be the front page, and a general summery of the technic mod.

**Comment by benrob0329** [comment]
Would something like this work for crafting recipes? Or should I do it all in GIMP?

![furnace_crafting](https://cloud.githubusercontent.com/assets/19180682/15227407/12deb626-1855-11e6-8c46-383dbdddff16.png)

**Comment by VanessaE** [comment]
That's exactly what I do in homedecor's crafting guide ( https://daconcepts.com/vanessa/hobbies/minetest/homedecor-crafting-guide/homedecor-craft-guide.html ).  Minetest -> Maximize window -> take screenshot -> GIMP:crop and save.

**Comment by benrob0329** [comment]
Alright, I'll need to turn off mipmapping though, It tends to scale down textures a bit too much sometimes.

**Comment by VanessaE** [comment]
Also, if you check the css of that page, you can see how I got the drop shadows and rounded corners.

**Comment by benrob0329** [comment]
https://github.com/minetest-technic/technic/wiki

It's a start!

**Comment by benrob0329** [comment]
https://github.com/minetest-technic/technic/wiki/Machines

**Comment by benrob0329** [comment]
I'm thinking about scrapping the current wiki and compleatly redoing it, with a page for each thing or group of things (furnaces, wire, solar panel) along with some getting started/article type pages.

**Comment by thePalindrome** [comment]
I'd also put the custom images somewhere else, possibly a special branch, that way the image host can't 404 the wiki 😄

**Comment by benrob0329** [comment]
The images are on my personal OwnCloud account on a friends server, so no worries there.

I guess I could use the path to the raw files in a GitHub repo, if that's preferred.

**Comment by VanessaE** [comment]
Wiki looks fine these days, apparently thanks to @benrob0329 :)
