### ISSUE TITLE
Ability to carry a charge?

### ISSUE THREAD

**Issue by thePalindrome** [minetest-technic/technic#284]
Playing around with drills and lasers and flashlights is all well and fun when you're some two kilometers away from home, but what do you do when you run out of power?

I would suggest the ability to have charged RE-batteries charge your devices so long as they are all in your inventory!

This does assume that items in the inventory get a few callbacks, but I would like some way to carry charge without having a battery box, a switching station, and two wires taking up space!

**Comment by benrob0329** [comment]
Or perhaps the ability to craft a flashlight + two charged batteries to get a charged flashlight, leaving two dead batteries in the crafting grid.

**Comment by thePalindrome** [comment]
I'd say that's a solution, albiet not ideal.
What I'd like is something more akin to the batpack from IndustrialCraft, where your items just stay charged.

**Comment by benrob0329** [comment]
So like a solar powered packpack?

**Comment by thePalindrome** [comment]
Not necessarily, a solar backpack wouldn't have use underground after all!

I'm thinking of a more extensible system allowing things like extra batteries that charge devices, or even something like a kinetic generator.

**Comment by benrob0329** [comment]
Hmmmmm.....so some kind of a small generator, possibly combined with battery packs to charge/power devices like the power packs used in old lightsabers....

I think I'm going to think on this for aa while...

**Comment by t4im** [comment]
Just carry a batterybox and a powercrystal with you. Placing it quickly to transfer the charge is simple enough.
