### ISSUE TITLE
enable/disable converter

### ISSUE THREAD

**Issue by DanHolli123** [minetest-technic/technic#285]
there should be an option for enabling and disabling the power converters or disable the 10000 discharge if not used

**Comment by numberZero** [comment]
Yes, just as in force field emitter (that can be controlled manually or by mesecon signal). That would be much more handy than using pistons.

**Comment by DanHolli123** [comment]
or without mesecons just right clicking

**Comment by numberZero** [comment]
Created corresponding pull request.

@DanHolli123 if running own server, you can check out [my updated version](https://github.com/numberZero/technic/tree/control-supply_converter) right now (the `control-supply_converter` branch)

**Comment by DanHolli123** [comment]
It's for personal use but I'll give it a try!

**Comment by VanessaE** [comment]
Fixed with #288
