### ISSUE TITLE
lava cooling ruins geothermal generators

### ISSUE THREAD

**Issue by cyisfor** [minetest-technic/technic#286]
You can't put water and lava at corners to each other now. It's in the default game under mods/default/functions.lua that lava turns to stone or obsidian if within 1 block (including corners) of water. Thus, geothermal generators can only have at most 25% power. Please make them 100% power with just 1 lava and 1 water on opposite ends to each other. Or else, allow for the lava to be at corners to the generator itself, like:
```
L X W
X G X
W X L
```
X = solid
L = lava
W = water
G = generator

The current way just doesn't work:
```
X L X
W G L
X W X
```
turns to
```
X O X
W G O
X W X
```
O = obsidian

Using flowing lava and flowing water doesn't help, just turns to stone instead of obsidian.

**Comment by asl97** [comment]
@cyisfor it has always been that way since [2014](https://github.com/minetest-technic/technic/commit/1d46d71b25a29dd5dc84298ebf794ab289e433b7)

some server use mods like [gloopblocks to override the lava cooling behaviour](https://github.com/minetest-mods/gloopblocks/blob/master/init.lua#L746)

**Comment by t4im** [comment]
There is at least one design, that uses less space and still gets to 100%. So this isn't really an issue.

**Comment by cyisfor** [comment]
@t4lm
oh, that's fantastic t4lm! That way would work, without having to change the code at all! I guess this isn't so much an issue then. I just didn't know the way to set them up. brb fixing my nodes

@asl97 
right, well, the point is the behavior would have to be changed so that it checked corners instead of faces, if there was no way to use geothermal generators as-is.
