### ISSUE TITLE
LV, MV, HV tools

### ISSUE THREAD

**Issue by kpoppel** [minetest-technic/technic#29]
How about letting the different tools only charge in the battery tier they belong to?
The laser should really be a MV or HV thing considering the power it packs.
The chainsaw an LV item, the sonic screwdriver perhaps a HV tem?

The chargers should then be upgradable with more slots or faster charging or something like that. I think some of the MV machines have this feature.

I suggest this because it doesn't make much sense for instance charging a 5V device directly on the 230V mains, right? (blue smoke!)

Opinions?

**Comment by yo-we** [comment]
Is this discussion still active?
