### ISSUE TITLE
[Patch] Undeclared Global Variable "unified_inventory"

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-technic/technic#293]
I wanted to suggest the following patch:

[technic-machines__register__recipes.lua.diff.zip](https://github.com/minetest-technic/technic/files/417413/technic-machines__register__recipes.lua.diff.zip)
- Wraps code in 'if minetest.get_modpath("unified_inventory")' before trying to access global variable
  - Fixes 'Undeclared global variable "unified_inventory"'

**Comment by HybridDog** [comment]
no, you should rather use minetest.global_exists

**Comment by AntumDeluge** [comment]
Thank you. I'll try that out & close this issue when I get a chance.

**Comment by VanessaE** [comment]
No further response from the author.  Closing...

**Comment by HybridDog** [comment]
@ShadowNinja forget to close this l assume.
https://github.com/minetest-technic/technic/commit/e393617fa1a7128993d3728ac6edb903d2ed7366

**Comment by AntumDeluge** [comment]
I apologize. I have been working on other projects & forgot about this.
