### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by kruug** [minetest-technic/technic#299]
When exploring new areas of a world with the technic mod enabled, every so often the game will "crash" with the error message:

Lua: OOM error from mod 'technic_worldgen' in callback environment_OnGenerated(
): not enough memory
Current Lua memory usage: 31MB

The memory usage is not constant.  I've seen as low as 28MB and as high as 45MB.

This is using the Minetest Game engine and V6 worldgen.

**Comment by yumetodo** [comment]
```
2016-10-23 12:21:46: ERROR[Main]: ServerError: Lua: OOM error from mod 'technic_worldgen' in callback environment_OnGenerated(): not enough memory
2016-10-23 12:21:46: ERROR[Main]: Current Lua memory usage: 54 MB
```

mintest was crashed because of same error.

## version
minetest : 0.4.14
technic : https://github.com/minetest-technic/technic/tree/63efc395cd1496acbbd960c3e0e0701142abdcec

**Comment by kruug** [comment]
This appears to be an issue with Minetest's LuaJIT world generator.  Using a build without LuaJIT does not result in a crash.

**Comment by Fixer-007** [comment]
Same problem appears when using technic bundled with dreambuilder modpack. Unfortunately thats general problem of luajit that offers very limited ram.

This needs some kind of workaround.

**Comment by MT-Modder** [comment]
I was having the same issue then found out minetest wasn't using my dedicated GPU. Did some fiddling with settings and now I don't have this issue. Hopes this helps some people.

**Comment by kruug** [comment]
@MT-Modder What settings did you change?  It would be helpful to others if you shared this.

https://xkcd.com/979/

**Comment by ShadowNinja** [comment]
LuaJIT can't use much memory and the exact limit is unpredictable (I think it has something to do with it depending on 32-bit pointers internally, and the amount of memory it can use depends on where LuaJIT is loaded by the OS).  Using regular Lua will fix this issue.
Closing since this isn't a Technic issue but rather a LuaJIT issue.

**Comment by MT-Modder** [comment]
The settings are going to be different for every GPU (it wasn't a setting in minetest). I have a 4gb nvidia Geforce gtx 960m. I opened up the nvidia control panel, went under "manage 3d settings", "program setttings", added minetest and set it to the nvidia card instead of the intel 1gb one.

**Comment by MT-Modder** [comment]
@Fixer-007 If it is I wouldn't know. I assumed LuaJIT ate though the 1gb very quickly and when I switched to the 4gb it had more to work with. All I know is that's what I changed and that's what fixed it for me.

Either way @ShadowNinja is right this isn't technic's problem.
