### ISSUE TITLE
supply converter : LV -> MV not working

### ISSUE THREAD

**Issue by lonevetad** [minetest-technic/technic#300]
As the title suggests, the supply converter does not convert a low voltage to medium voltage, even if it's well connected and both voltage has their own switching station.

**Comment by Cyberpangolin** [comment]
I am currently trying to make it, it works perfectly to me.
BUT
the supply converter needs 10k EU to give 9k EU on a single, which means **you must have at last a battery box at both sides**. (1 LV + 1MV battery box) or a huge LV power plant producing more than 10k EU / second. Without any battery box, the switching station will consume almost all the produced energy without any output.

Furthermore, if you generate all your MV trough a LV network, I strongly recommend you to use a separate LV network for your LV machines, or they will lack energy: as soon as 10k EU are stored into the LV battery box, they will be sent to the MV part.

**Comment by VanessaE** [comment]
This isn't an issue anymore as far as I can tell.
