### ISSUE TITLE
Quarry and mods Protector = crash server

### ISSUE THREAD

**Issue by d-stephane** [minetest-technic/technic#303]
Hello,

I have a problem:
if a quarry is used on a protected area by the MOD “Protector” (https://github.com/tenplus1/protector) the server crash...
The protected area belongs to the same player as the quarry
Test made on a server in version 0.4.14-Dev.-2ff054d (Linux)
Here the error:

<pre>2016-12-07 09:04:25: ERROR[Main]: ServerError: Lua: Runtime error from mod '' in callback LuaABM::trigger(): ...etest/minetest-0.4.14/bin/../mods/protector/init.lua:443: attempt to index local 'player' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: ...etest/minetest-0.4.14/bin/../mods/protector/init.lua:443: in function 'can_dig'
ERROR[Main]: ..../mods/technic-master/technic/machines/HV/quarry.lua:153: in function 'technic_run'
ERROR[Main]: ...echnic-master/technic/machines/switching_station.lua:220: in function 'run_nodes'
ERROR[Main]: ...echnic-master/technic/machines/switching_station.lua:226: in function <...echnic-master/technic/machines/switching_station.lua:172>`

**Comment by Ryan-Nolan** [comment]
Ive not had the chance to take a proper look at this. But at a quick glance 
 The problem looks to be with the “Protector" mod and not with technic... I may be wrong, just a quick observation

**Comment by d-stephane** [comment]
Possible. For the moment i removed the protector mod...
