### ISSUE TITLE
An empty file named 'origin' is in the repository

### ISSUE THREAD

**Issue by silwol** [minetest-technic/technic#319]
I assume the file landed there by accident. This causes the following command to fail:
```
git reset --hard origin
fatal: ambiguous argument 'origin': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
I stumbled over this problem because I use ansible to manage my minetest server, and it uses this exact command for managing the git repository.

**Comment by kaeza** [comment]
File? What file?
