### ISSUE TITLE
Mining drill modes not switchable? [Unconfirmed]

### ISSUE THREAD

**Issue by Ekdohibs** [minetest-technic/technic#332]
See http://irc.minetest.ru/minetest-project/2017-03-27#i_4840726

**Comment by kaeza** [comment]
Cannot reproduce myself. All drills work as (what I suppose) is expected.

* Mk1 drill can't switch mode.
* Mk2 drill goes 1-4.
* Mk3 drill goes 1-5.

Am I missing something?

**Comment by thatgraemeguy** [comment]
This was fixed in #314.

**Comment by kaeza** [comment]
I guess this can be closed then. @Ekdohibs ?
