### ISSUE TITLE
Lua voxelmanip memory optimisation to reduce OOMs

### ISSUE THREAD

**Issue by paramat** [minetest-technic/technic#337]
Sulfur generation:
https://github.com/minetest-technic/technic/blob/master/technic_worldgen/oregen.lua#L118

You can reduce memory use a lot by using the 'data buffer optimisation' detailed here in point 3 https://forum.minetest.net/viewtopic.php?f=18&t=16043
It's very simple.

**Comment by VanessaE** [comment]
Thanks for the help with this, @paramat.

eb344ad804aa83570ccda9a5886733d8b42aa598
