### ISSUE TITLE
Charging station idea.

### ISSUE THREAD

**Issue by kpoppel** [minetest-technic/technic#54]
With tools at different supply levels I suggest adding a proper charging bench which can charge the tools thus eliminating the charging functionality from the batteries.

Requiring energy for lighting etc. requires whole banks (rooms!) of batteries and as such it becomes unwieldy to use them as charging benches.

All supply tiers can be changed regardless of the supply network it is placed on.
However(!): the same conversion restrictions the supply converter has applies here.
LV supply will charge a MV tool at 1/4 charge, and HV at 1/16 charge
MV supply will charge a LV tool 5x faster and HV tool at 1/4 charge
HV supply will charge a LV and MV tool 5x faster.
 5x is max boost a battery in a tool can handle if it should not burst into flames.

The machine will need some plugins to function:
 LV/MV/HV charging modules opening LV, MV, and HV charging.
 Each charging module will add 2 charging slots.

4 expansion slots are provided for a total of 8 charging slots per machine.

Implementation wise it is much the same as the supply converter in regards to detecting what kind of supply network it is put on.

Comments?

**Comment by HybridDog** [comment]
Why is it closed?

**Comment by VanessaE** [comment]
No recent response from the original author, and note what RBA last said.
