### ISSUE TITLE
Solars seem to no longer work when in an inactive block

### ISSUE THREAD

**Issue by chlue** [minetest-technic/technic#90]
tested with: 468d79db617c663043dba26d2be2d738089725f9

Solar in inactive blocks no longer work. Typical example are solars placed over the clouds at 130. They used to produce power but don't update their state (even work at night when last visited at day) as long as the switching station was in an active block. Now they seem to not work at all.

Additionally solars need to be placed above 0 and have already max power at a high of 35 now while the comments in the code still say > -10, max @ 130

**Comment by Ekdohibs** [comment]
Closing, as this should be fixed now
