### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Xiong** [minetest-technic/technic#94]
My father was an old mainframe guy -- really. I was inducted into the mysteries not merely of the 80-column Hollerith card but of the obscure control card drum behind a discreet door in the keypunch machine. At home, we used 132-column greenbar fanfold for scratch paper. 

When I was just starting out -- as a hardware dog but, as a microelectronics guy, constantly brushing into software of some sort -- Pop gave me one piece of advice that has always stuck with me, and which I consider a tenent of my only religion: 

*"One line of comment per line of code."* -- probably originally from IBM

I should explain that to get your score, you count blank lines as zero, code lines with trailing comments as zero, code lines without comments as -1, and "block" comments or comment-only lines as +1. The goal is to achieve a score of roughly zero. 

Kids scorn comments and think that rule is nonsense. They write entire undocumented subroutines and say, *"Anybody can understand that self-documenting code, because my writing is so clear."* 

**BULLSHIT.**

I agree that as we move away from FORTRAN towards C and Ruby, we probably need a bit fewer comments than in the old days. But not much. Yes, the code itself is more readable but the task it performs is more complex. The amount of explanation required is about the same. 

Nobody is sure who said this first: *"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live."* However, it is gospel. That maintainer may very well be you. It might be me. 

However, I didn't start here to talk about comments in code. I started to talk about documentation. Docs are distinct from comments. As I said recently to a fellow, code is written for the machine; comments are written for developers; docs are written for users. 

And if you don't have users, then your code is worthless, eh?

I'm going to keep this issue short because I've already promised to take up the burden of documenting 'technic'... provided we get some agreement on this and the other two heads of a solution to my rant-problem. However, I can't do it alone. So, some principles: 

* Docs need to be in some sort of content management system. One big web page is not that. I uphold wikis, specifically the MediaWiki engine, because it is fast and powerful. Wikis, unlike BB-style forums, downplay egos and provide a high signal-to-noise ratio. Navigation is easy and deadwood easily archived out of sight. Please do not judge all wikis by the wikis you may have seen, especially not by Wikipedia. That latter suffers from the crushing burden of "Anyone can edit"; and if everyone could agree on anything, we wouldn't have wars in which poison gas is employed against civilians who worship in the wrong direction. Wikis work best when the group is fairly small -- such as the number of people who use 'technic'. 

* Docs are everyone's responsibility. I'm willing to take a big bite out of the task... and there should indeed be some one person carrying the can. But docs are good when everyone on the team makes them good. It simply is not acceptable to write code and turn it over, saying "This does neat stuff, buy it." Every new feature, every patch, every pull request should be accompanied by as much plain English as is needed to explain what the thing does. This might be pretty rough and you can leave it up to the dedicated docs man to clean it up and fit it into the docs package. But you cannot just drop code into the project with a one-line explanation. 

* That said, I'm not above reading code when writing docs. Help me out. Don't hope I have a telepathic connection to your head of a week ago. Comment, comment, comment. Yes -- I tell you again -- your code is not self-documenting. Really, it's not. Yes, really. You need to commment it. What if you get hit by a bus tomorrow? What if I have to maintain it some day? What if I know where you live? 

* Docs must be kept accurate. As the underlying project changes, so must the docs. But how is that possible if the code changes every day? Well, the docs cannot document every new fiddle -- it's impossible. There will always be some lack of synchronization with the bleeding edge. However, docs *can* accurately reflect the code at some given point. We call that point a "release" and we need to take that concept seriously -- for this reason alone, ignoring all others. It's perfectly okay to have more than one version of the same docs -- one version of the docs for each release of the project. Yes. 

* Docs are meant to be read by users -- by definition, people who do not develop the project. Therefore it is inexcusable to refer to the code or use terms that don't apply outside the code base. As much as possible, docs must be written in end-user terms. We can tolerate imprecision; it's accuracy we require of docs. 

Software should not be a puzzle that users try to solve, a knot that they pick at for days or weeks trying to unravel. Software, like any other tool, is most useful if users can figure out easily how to use it to best advantage. I will not be the person to inveigh against masturbation; but sex with other people is better. And writing software that other people enjoy using is better than writing cool code that amuses only yourself.

**Comment by yo-we** [comment]
Thank you for formulating this and for keeping this subject visible. And thank you for documenting your code (inside code files and outside). It makes it accessible, even for people not writing code.
