### ISSUE TITLE
Proposal for different switching station recipe (and splitting in lv, mv and hv variant)

### ISSUE THREAD

**Issue by chlue** [minetest-technic/technic#97]
I propose to add three different switching stations. While this makes things more complicated it reduces the issue a bit that the first switching station should be reasonable simple to get without completely spoiling the 'fun' for later.

Idea for the recipe is:
control logic unit at the top and three wire in/outputs. If the voltage is not lv a transformer is necessary to not fry the control logic unit. This is still horrible oversimplified, but on the other hand real current would find its way on its own,..

lv (no transformer needed here):
{'default:steel_ingot', 'technic:control_logic_unit',  'default:steel_ingot'},
{'technic:lv_cable0',   'technic:lv_cable0',           'technic:lv_cable0'},
{'default:steel_ingot', 'technic:lv_cable0',           'default:steel_ingot'},

mv:
{'technic:stainless_steel_ingot', 'technic:control_logic_unit',  'technic:stainless_steel_ingot'},
{'technic:mv_cable0',             'technic:mv_transformer',      'technic:mv_cable0'},
{'technic:stainless_steel_ingot', 'technic:mv_cable0',           'technic:stainless_steel_ingot'},

hv:
{'technic:stainless_steel_ingot', 'technic:control_logic_unit', 'technic:stainless_steel_ingot'},
{'technic:hv_cable0',             'technic:hv_transformer',     'technic:hv_cable0'},
{'technic:stainless_steel_ingot', 'technic:hv_cable0',          'technic:stainless_steel_ingot'},

**Comment by yo-we** [comment]
Just in case you still follow your idea of having separate switching stations per source voltage tier: I like the initial idea. To resolve the dependency problems, you could modify the recipes like this:
 1.) For the metal in use, I would propose cast iron(LV), carbon steel(MV) and stainless steel(HV).
 2.) To have a dependency free LV switching station, just replace the control logic unit (for LV only) by say 2 mese blocks. This is still moderately expensive.
Personally, I would prefer a "lv_transformer" being used for the LV switching station.

 The use of the control logic unit is justified for me. First of all this increases the complexity of the recipe. And then, a switching station does calculate the supply and the need.

**Comment by VanessaE** [comment]
Switching stations function more like a network router than an actual transformer/switch/substation, and going to a three-tiered strategy would break technic installations all over the place.  Closing.
